// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOaa1Qz_HSHWfRAr8F0FOX5sWSqqtU_MM',
    appId: '1:210442734122:web:99aaad9637a9343df39153',
    messagingSenderId: '210442734122',
    projectId: 'diu-events-app',
    authDomain: 'diu-events-app.firebaseapp.com',
    storageBucket: 'diu-events-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbb9AhJ969PUC9MTER9bibf2VqSRfgjLA',
    appId: '1:210442734122:android:6c32c51591e986a7f39153',
    messagingSenderId: '210442734122',
    projectId: 'diu-events-app',
    storageBucket: 'diu-events-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXISylZL7gpyH-1ROd6VywJdEGtym18m8',
    appId: '1:210442734122:ios:5eeda1a815877c1df39153',
    messagingSenderId: '210442734122',
    projectId: 'diu-events-app',
    storageBucket: 'diu-events-app.firebasestorage.app',
    iosBundleId: 'com.example.diuEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXISylZL7gpyH-1ROd6VywJdEGtym18m8',
    appId: '1:210442734122:ios:5eeda1a815877c1df39153',
    messagingSenderId: '210442734122',
    projectId: 'diu-events-app',
    storageBucket: 'diu-events-app.firebasestorage.app',
    iosBundleId: 'com.example.diuEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOaa1Qz_HSHWfRAr8F0FOX5sWSqqtU_MM',
    appId: '1:210442734122:web:044fc18114cdec7bf39153',
    messagingSenderId: '210442734122',
    projectId: 'diu-events-app',
    authDomain: 'diu-events-app.firebaseapp.com',
    storageBucket: 'diu-events-app.firebasestorage.app',
  );

}